---
title: "Desempeño en ventas"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(dplyr)
library(DT)
library(formattable)
library(ggplot2)
library(graphics)
library(crosstalk)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
mi_tienda <- read.csv('tienda.csv',stringsAsFactors = FALSE) %>%
  rename_with( ~ tolower(gsub(".","_",.x,fixed = TRUE)))

mi_tienda$sales <- sub(",","",mi_tienda$sales)
mi_tienda$profit <- sub(",","",mi_tienda$profit)

mi_tienda[,c("order_date","ship_date","sales","profit","year",'cost')] <- as.data.frame(list(order_date = as.Date(mi_tienda$order_date,'%m/%d/%Y'),
       ship_date = as.Date(mi_tienda$ship_date,'%m/%d/%Y'),
       sales = as.numeric(mi_tienda$sales),
       profit = as.numeric(mi_tienda$profit),
       year = format(as.Date(mi_tienda$order_date,'%m/%d/%Y'),'%Y')
       )) %>%
  mutate(cost = sales-profit)


```

# Productos


Column {data-width=600}
-----------------------------------------------------------------------

### Productos destacados

```{r echo=FALSE}
## DataShared para definir los productos más rentables
data_top <- SharedData$new(mi_tienda %>%
                             group_by(year, sub_category,product_name) %>%
                             filter(!is.na(profit) & 
                                      !is.na(sales))%>%
                             dplyr::summarise(profit = sum(profit)/sum(cost))%>%
                             arrange(desc(profit)))

# Aplicación de filtros
filter_select("dt","Año",data_top,group = ~year, multiple = FALSE)

filter_select("ctr","Subcategoría", data_top, group = ~sub_category, multiple = FALSE)


## Mostrar las tablas
data_top %>%
  DT::datatable(rownames = FALSE, 
                filter = "none",
                colnames = c('Year','Subcategoria','Nombre del producto','Rendimiento'),
                
                options = list(dom = 't',
                               columnDefs = list(list(targets = "year", visible = FALSE),
                                                 list(targets = "sub_category", visible = FALSE)),
                               pageLength = 1,
                               initComplete = JS("function(settings, json) {",
                                                 "$(this.api().table().header()).css({'background-color': '#26580F', 'color': '#fff'});",
                                                 "}")))%>%
  formatPercentage('profit',digits = 2) %>%
  formatStyle('profit', backgroundColor = '#F0FFF0', fontWeight = 'bold')%>%
  formatStyle('product_name',  color = 'gray', fontWeight = 'bold')

```

```{js}
function filter_default() {
    document.getElementById(dt).getElementsByClassName("selectized") 
[0].selectize.setValue(2014, false);
 }
window.onload = filter_default;
```

Column {data-width=350, data-height}
-----------------------------------------------------------------------

### Gráfico

```{r}


```

### Chart C

```{r}

```


# Segmentos

Column {data-width=600}
-----------------------------------------------------------------------

### Rendimiento

```{r}
Segmentos <- mi_tienda %>%
  filter(!is.na(profit) &
           !is.na(cost) &
           !is.na(year))%>%
  group_by(year, segment)%>%
  dplyr::summarise(Ganancias = sum(profit),
                   Costos = sum(cost)) 
#%>%
 # ggplot(mapping = aes(x="segment",y='profit'), type = 'bar') +
  #geom_ba
  

```